import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cleven | Orchestrating Solutions Beyond the Obvious ",
  description: "Generated by create next app",
};
const raleway = Raleway({
  subsets: ["latin-ext"],
  weight: "700",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#0c0c0c] ${raleway.className}`}>
        {children}
      </body>
    </html>
  );
}
